### ISSUE TITLE
buttonsStyle textes Error un Documentation

### ISSUE THREAD

**Issue by andresamayadiaz** [Flowrome/electron-multi-prompt#1]
Just a small type, In the README you have this as example:
buttonsStyle: {
      ok_color: '#color_code', //color for ok text button
      cancel_color: '#color_code', //color for cancel text button
      ok_bg_color: '#color_code', //color for ok button
      cancel_bg_color: '#color_code', //color for cancel button
      textes: {
        **ok_text: 'text', //text for ok button
        cancel_text: 'text' //text for cancel button**
      }
    },

When the correcto should be this:
buttonsStyle: {
      ok_color: '#color_code', //color for ok text button
      cancel_color: '#color_code', //color for cancel text button
      ok_bg_color: '#color_code', //color for ok button
      cancel_bg_color: '#color_code', //color for cancel button
      textes: {
        **ok_txt: 'text', // >>>> ok_txt instead of ok_text
        cancel_txt: 'text' // >>>> cancel_txt instead of ok_text**
      }
    },

**Comment by Flowrome** [comment]
Hi @andresamayadiaz Thank you for checking the typo :)
